App
ilya-burinskiy/gophermart pull request #1
Opened 2024-01-24 16:13 UTC by ilya-burinskiy

2024-01-25 17:11 UTC, maxlyaptsev requested changes

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/auth/auth.go
> +const TokenExp = 24 * time.Hour
лучше вынести в конфиги

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func setJWTCookie(w http.ResponseWriter, token string) {
кажется лучше в auth переместить, тут файл может потеряться в ручках

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/models/order.go
> +	}
а почему бы просто не использовать статус как строковый тип? Было бы удобней и читаемей, в бд это все равно enum

type OrderStatus string

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/services/accrual.go
> +		channel: make(chan models.Order),
канал без буфера, соответственно в Register будет лок пока не освободится место (пока не станет пустым)
А воркер будет постоянно голодным, увеличив количество воркеров не повысим производительность т.к. в канале будет только один заказ и его быстро кто-то заберет. Так что тут я бы подумал о буфере. Но нужно помнить что при остановке приложения канал чистится вместе с буфером

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/services/createorder.go
> +	srv.accuralSrv.Register(order)
что будет если не получилось тут положить заказ? В бд он есть, а в сервисе не окажется и больше мы его не получим

Внутри есть ожидание канала, если канал не пустой то будем ждать обработки, а это синхронная работа и смысл канала пропадает

2024-01-25 17:11 UTC, maxlyaptsev commented on internal/services/createorder.go
> +	Call(ctx context.Context, number string, userID int) (models.Order, error)
nit: Вижу что в сервисах это единственный метод и называние сервиса содержит его функционал, но все же если давать функциям понятные имена - так просто будет легче читать. Читая Call всегда нужно держать в уме с каким сервисом работаем и стараться догадаться что должны сделать. А еще будет сложно расширять ели все же понадобится какой-то метод

order.Create / order.Update / order.Delete в одном сервисе будет удобней чем
orderCreator.Call / orderUpdater.Call / orderDeleter.Call

2024-01-26 14:38 UTC, ilya-burinskiy commented on internal/models/order.go
> +	}
хз) когда писал на рельсах, то енамы реализовывал через инты

2024-01-26 14:50 UTC, ilya-burinskiy commented on internal/services/createorder.go
> +	Call(ctx context.Context, number string, userID int) (models.Order, error)
тут тоже привычка с рельс. метод `Call` был методом класса и вызывался так `OrderCreater.call(...)`

2024-01-29 21:23 UTC, maxlyaptsev commented on internal/services/createorder.go
> +	srv.accuralSrv.Register(order)
Вот эта проблема осталась 
1.  если в канале нет места - то в ручке будет блокировка пока место в канале не освободится
2. если приложение завершится жестко, то вместе с ним пропадут заказы, которые еще не успели обработать

2024-01-31 13:04 UTC, maxlyaptsev commented on internal/services/accrual.go
> +	ticker := time.NewTicker(5 * time.Second)
все подобные вещи лучше сразу в конфиг выносить

2024-02-05 17:50 UTC, merged